
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Casper
 */
public class levelThreeGameLoad extends javax.swing.JFrame {

    /**
     * Creates new form oyunSeviyeUcYukleme
     */
    public levelThreeGameLoad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oyunSeviyeUcYukleme = new javax.swing.JPanel();
        levelThreeGameLoadText = new javax.swing.JLabel();
        levelThreeGameLoadGif = new javax.swing.JLabel();
        levelThreeGameLoadBtn = new javax.swing.JLabel();
        levelThreeGameLoadExitLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        oyunSeviyeUcYukleme.setBackground(new java.awt.Color(240, 234, 224));
        oyunSeviyeUcYukleme.setLayout(null);

        levelThreeGameLoadText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        levelThreeGameLoadText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-submit-progress-48.png"))); // NOI18N
        levelThreeGameLoadText.setText("Level III load");
        oyunSeviyeUcYukleme.add(levelThreeGameLoadText);
        levelThreeGameLoadText.setBounds(130, 50, 210, 50);
        oyunSeviyeUcYukleme.add(levelThreeGameLoadGif);
        levelThreeGameLoadGif.setBounds(170, 120, 170, 80);

        levelThreeGameLoadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameGreenBtn.png"))); // NOI18N
        levelThreeGameLoadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelThreeGameLoadBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                levelThreeGameLoadBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                levelThreeGameLoadBtnMouseExited(evt);
            }
        });
        oyunSeviyeUcYukleme.add(levelThreeGameLoadBtn);
        levelThreeGameLoadBtn.setBounds(150, 220, 170, 70);

        levelThreeGameLoadExitLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-24.png"))); // NOI18N
        levelThreeGameLoadExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                levelThreeGameLoadExitLblMouseClicked(evt);
            }
        });
        oyunSeviyeUcYukleme.add(levelThreeGameLoadExitLbl);
        levelThreeGameLoadExitLbl.setBounds(430, 10, 24, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oyunSeviyeUcYukleme, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oyunSeviyeUcYukleme, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int say = 0;
    private void levelThreeGameLoadBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelThreeGameLoadBtnMouseClicked
        // TODO add your handling code here:
        Timer timer = new Timer(75, null);
        timer.addActionListener((ActionEvent e) -> {
            say += 5;
            levelThreeGameLoadText.setText("Level III is loading...");
            levelThreeGameLoadGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Infinity.gif")));
            if (say == 400) {
                timer.stop();
                try {
                    JOptionPane.showMessageDialog(rootPane, "Level III loaded", "Game Load", JOptionPane.INFORMATION_MESSAGE);
                    new gameSelection().gamePlayLevelThree();
                    setVisible(false);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Unexpected a situation has been occurred." + ex.getMessage());
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_levelThreeGameLoadBtnMouseClicked

    private void levelThreeGameLoadBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelThreeGameLoadBtnMouseEntered
        // TODO add your handling code here:
        levelThreeGameLoadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameBlueBtn.png")));
    }//GEN-LAST:event_levelThreeGameLoadBtnMouseEntered

    private void levelThreeGameLoadBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelThreeGameLoadBtnMouseExited
        // TODO add your handling code here:
        levelThreeGameLoadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameGreenBtn.png")));
    }//GEN-LAST:event_levelThreeGameLoadBtnMouseExited

    private void levelThreeGameLoadExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_levelThreeGameLoadExitLblMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_levelThreeGameLoadExitLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Hata Olustu, Hata Nedeni " + ex.getMessage(), "Hata", JOptionPane.ERROR);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new levelThreeGameLoad().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel levelThreeGameLoadBtn;
    private javax.swing.JLabel levelThreeGameLoadExitLbl;
    private javax.swing.JLabel levelThreeGameLoadGif;
    private javax.swing.JLabel levelThreeGameLoadText;
    private javax.swing.JPanel oyunSeviyeUcYukleme;
    // End of variables declaration//GEN-END:variables
}
