
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Casper
 */
public class levelTwoGameLoad extends javax.swing.JFrame {

    private int counter = 0;

    /**
     * Creates new form Yükleme
     */
    public  levelTwoGameLoad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameLoadLevelTwoPanel = new javax.swing.JPanel();
        gameLoadLevelTwoText = new javax.swing.JLabel();
        gameLoadLevelTwoExitLbl = new javax.swing.JLabel();
        gameLoadLevelTwoBtn = new javax.swing.JLabel();
        gameLoadLevelTwoGif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setUndecorated(true);
        setResizable(false);

        gameLoadLevelTwoPanel.setBackground(new java.awt.Color(240, 234, 224));
        gameLoadLevelTwoPanel.setLayout(null);

        gameLoadLevelTwoText.setBackground(java.awt.Color.darkGray);
        gameLoadLevelTwoText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        gameLoadLevelTwoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-submit-progress-48.png"))); // NOI18N
        gameLoadLevelTwoText.setText("Level II load");
        gameLoadLevelTwoPanel.add(gameLoadLevelTwoText);
        gameLoadLevelTwoText.setBounds(100, 50, 280, 48);

        gameLoadLevelTwoExitLbl.setBackground(java.awt.Color.darkGray);
        gameLoadLevelTwoExitLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-24.png"))); // NOI18N
        gameLoadLevelTwoExitLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameLoadLevelTwoExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameLoadLevelTwoExitLblMouseClicked(evt);
            }
        });
        gameLoadLevelTwoPanel.add(gameLoadLevelTwoExitLbl);
        gameLoadLevelTwoExitLbl.setBounds(430, 10, 24, 23);

        gameLoadLevelTwoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameGreenBtn.png"))); // NOI18N
        gameLoadLevelTwoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameLoadLevelTwoBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gameLoadLevelTwoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gameLoadLevelTwoBtnMouseExited(evt);
            }
        });
        gameLoadLevelTwoPanel.add(gameLoadLevelTwoBtn);
        gameLoadLevelTwoBtn.setBounds(150, 260, 170, 50);
        gameLoadLevelTwoPanel.add(gameLoadLevelTwoGif);
        gameLoadLevelTwoGif.setBounds(170, 120, 150, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameLoadLevelTwoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameLoadLevelTwoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameLoadLevelTwoExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelTwoExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_gameLoadLevelTwoExitLblMouseClicked

    private void gameLoadLevelTwoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelTwoBtnMouseClicked
        // TODO add your handling code here:
        Timer timer = new Timer(75, null);
        timer.addActionListener((ActionEvent e) -> {
            counter += 5;
            gameLoadLevelTwoText.setText("Level II is loading...");
            gameLoadLevelTwoGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Infinity.gif")));
            if (counter == 400) {
                timer.stop();
                try {
                    JOptionPane.showMessageDialog(rootPane, "Level II loaded","Oyun Yukleme",JOptionPane.INFORMATION_MESSAGE);
                    new gameSelection().gamePlayLevelTwo();
                    setVisible(false);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Unexpected  a situation has been occurred");
                }               
            }
        });
        timer.start();
    }//GEN-LAST:event_gameLoadLevelTwoBtnMouseClicked

    private void gameLoadLevelTwoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelTwoBtnMouseEntered
        // TODO add your handling code here:
        gameLoadLevelTwoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameBlueBtn.png")));
    }//GEN-LAST:event_gameLoadLevelTwoBtnMouseEntered

    private void gameLoadLevelTwoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelTwoBtnMouseExited
        // TODO add your handling code here:
        gameLoadLevelTwoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameGreenBtn.png")));
    }//GEN-LAST:event_gameLoadLevelTwoBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
           JOptionPane.showMessageDialog(null,"Unexpected a situation has been occurred:\nError : "+ex.getMessage(),"Error Message",JOptionPane.ERROR);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new levelTwoGameLoad().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameLoadLevelTwoBtn;
    private javax.swing.JLabel gameLoadLevelTwoExitLbl;
    private javax.swing.JLabel gameLoadLevelTwoGif;
    private javax.swing.JPanel gameLoadLevelTwoPanel;
    private javax.swing.JLabel gameLoadLevelTwoText;
    // End of variables declaration//GEN-END:variables
}
