
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Casper
 */
public class levelOneGameLoad extends javax.swing.JFrame {

    private int counter = 0;

    /**
     * Creates new form DosyaIndirme
     */
    public levelOneGameLoad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameLoadLevelOnePanel = new javax.swing.JPanel();
        gameLoadingLevelOneText = new javax.swing.JLabel();
        gameLoadLevelOneExitLbl = new javax.swing.JLabel();
        gameLoadLevelOneGif = new javax.swing.JLabel();
        gameLoadLevelOneBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dosya Indirme Simulasyonu");
        setBackground(java.awt.Color.darkGray);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        gameLoadLevelOnePanel.setBackground(new java.awt.Color(240, 234, 224));
        gameLoadLevelOnePanel.setLayout(null);

        gameLoadingLevelOneText.setBackground(new java.awt.Color(0, 0, 0));
        gameLoadingLevelOneText.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        gameLoadingLevelOneText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-submit-progress-48.png"))); // NOI18N
        gameLoadingLevelOneText.setText("Level I load");
        gameLoadLevelOnePanel.add(gameLoadingLevelOneText);
        gameLoadingLevelOneText.setBounds(110, 60, 310, 46);

        gameLoadLevelOneExitLbl.setBackground(java.awt.Color.darkGray);
        gameLoadLevelOneExitLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-24.png"))); // NOI18N
        gameLoadLevelOneExitLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gameLoadLevelOneExitLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameLoadLevelOneExitLblMouseClicked(evt);
            }
        });
        gameLoadLevelOnePanel.add(gameLoadLevelOneExitLbl);
        gameLoadLevelOneExitLbl.setBounds(430, 10, 24, 24);
        gameLoadLevelOnePanel.add(gameLoadLevelOneGif);
        gameLoadLevelOneGif.setBounds(170, 130, 190, 80);

        gameLoadLevelOneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameGreenBtn.png"))); // NOI18N
        gameLoadLevelOneBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameLoadLevelOneBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gameLoadLevelOneBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gameLoadLevelOneBtnMouseExited(evt);
            }
        });
        gameLoadLevelOnePanel.add(gameLoadLevelOneBtn);
        gameLoadLevelOneBtn.setBounds(140, 240, 170, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameLoadLevelOnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameLoadLevelOnePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Space War");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gameLoadLevelOneExitLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelOneExitLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_gameLoadLevelOneExitLblMouseClicked

    private void gameLoadLevelOneBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelOneBtnMouseClicked
        // TODO add your handling code here:
        Timer timer = new Timer(75, null);
        timer.addActionListener((ActionEvent e) -> {
            counter += 5;
            gameLoadingLevelOneText.setText("Level I is loading...");
            gameLoadLevelOneGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Infinity.gif")));
            if (counter == 400) {
                timer.stop();
                try {
                    JOptionPane.showMessageDialog(rootPane, "Level I loaded","Game Load",JOptionPane.INFORMATION_MESSAGE);
                    new gameSelection().gamePlayLevelOne();
                    setVisible(false);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "Unexpected  a situation has been occurred");
                }
                
            }
        });
        timer.start();

    }//GEN-LAST:event_gameLoadLevelOneBtnMouseClicked

    private void gameLoadLevelOneBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelOneBtnMouseEntered
        // TODO add your handling code here:
        gameLoadLevelOneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameBlueBtn.png")));
    }//GEN-LAST:event_gameLoadLevelOneBtnMouseEntered

    private void gameLoadLevelOneBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameLoadLevelOneBtnMouseExited
        // TODO add your handling code here:
        gameLoadLevelOneBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/installGameGreenBtn.png")));
    }//GEN-LAST:event_gameLoadLevelOneBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null,"Unexpected a situation has been occurred:\nError : "+ex.getMessage(),"Error Message",JOptionPane.ERROR);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new levelOneGameLoad().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gameLoadLevelOneBtn;
    private javax.swing.JLabel gameLoadLevelOneExitLbl;
    private javax.swing.JLabel gameLoadLevelOneGif;
    private javax.swing.JPanel gameLoadLevelOnePanel;
    private javax.swing.JLabel gameLoadingLevelOneText;
    // End of variables declaration//GEN-END:variables
}
